//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace syswin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("su.resource", typeof(resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

		/// <summary>
		///   Looks up a localized string similar to Version {0}.
		/// </summary>
		internal static string IDS_TITLE {
			get {
				return ResourceManager.GetString("IDS_TITLE", resourceCulture);
			}
		}

        /// <summary>
		///   Looks up a localized string similar to Rights: (c) 2014 Francis Korning (manufacture.net).
        /// </summary>
        internal static string IDS_COPYRIGHT {
            get {
                return ResourceManager.GetString("IDS_COPYRIGHT", resourceCulture);
            }
        }

		/// <summary>
		///   Looks up a localized string similar to License: (l) LGPL (Lesser GNU Public License).
		/// </summary>
		internal static string IDS_LICENSING {
			get {
				return ResourceManager.GetString("IDS_LICENSING", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to This usage and options help message (/?).
		/// </summary>
		internal static string IDS_OPT_help {
			get {
				return ResourceManager.GetString("IDS_OPT_help", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to User under which to execute cmd shell.
		/// </summary>
		internal static string IDS_OPT_user {
			get {
				return ResourceManager.GetString("IDS_OPT_user", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Password to run cmd shell (no prompt).
		/// </summary>
		internal static string IDS_OPT_pass {
			get {
				return ResourceManager.GetString("IDS_OPT_pass", resourceCulture);
			}
		}

        /// <summary>
		///   Looks up a localized string similar to Cmd Shell executable to invoke (cmd|bash).
        /// </summary>
        internal static string IDS_OPT_shell {
            get {
                return ResourceManager.GetString("IDS_OPT_shell", resourceCulture);
            }
        }

		/// <summary>
		///   Looks up a localized string similar to Directory from which to run cmd shell.
		/// </summary>
		internal static string IDS_OPT_dir {
			get {
				return ResourceManager.GetString("IDS_OPT_dir", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Keep cmd shell interactive (default).
		/// </summary>
		internal static string IDS_OPT_keep {
			get {
				return ResourceManager.GetString("IDS_OPT_keep", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Login shell sourcing profile (default).
		/// </summary>
		internal static string IDS_OPT_login {
			get {
				return ResourceManager.GetString("IDS_OPT_login", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to raise local network credentials (excludes login !).
		/// </summary>
		internal static string IDS_OPT_netcr {
			get {
				return ResourceManager.GetString("IDS_OPT_netcr", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Use current env credentials (excludes login !).
		/// </summary>
		internal static string IDS_OPT_envcr {
			get {
				return ResourceManager.GetString("IDS_OPT_envcr", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Share and save credentials (sso prompt).
		/// </summary>
		internal static string IDS_OPT_savcr {
			get {
				return ResourceManager.GetString("IDS_OPT_savcr", resourceCulture);
			}
		}


		/// <summary>
		///   Looks up a localized string similar to Mimic and preserve environment variables (non login+).
		/// </summary>
		internal static string IDS_OPT_mimic {
			get {
				return ResourceManager.GetString("IDS_OPT_mimic", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to export additional environment variables (key[=value][,..]).
		/// </summary>
		internal static string IDS_OPT_envs {
			get {
				return ResourceManager.GetString("IDS_OPT_envs", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Additional cmd shell arguments.
		/// </summary>
		internal static string IDS_OPT_args {
			get {
				return ResourceManager.GetString("IDS_OPT_args", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Separator token char for envs and args (default comma ',').
		/// </summary>
		internal static string IDS_OPT_xtok {
			get {
				return ResourceManager.GetString("IDS_OPT_xtok", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Execute this chained cmd shell command.
		/// </summary>
		internal static string IDS_OPT_cmd {
			get {
				return ResourceManager.GetString("IDS_OPT_cmd", resourceCulture);
			}
		}


		/// <summary>
		///   Looks up a localized string similar to Elevating user to administrator.
		/// </summary>
		internal static string IDS_MSG_ElevatingUserToAdministrator {
			get {
				return ResourceManager.GetString("IDS_MSG_ElevatingUserToAdministrator", resourceCulture);
			}
		}

        /// <summary>
        ///   Looks up a localized string similar to Already running as administrator.
        /// </summary>
        internal static string IDS_MSG_AlreadyRunningAsAdministrator {
            get {
                return ResourceManager.GetString("IDS_MSG_AlreadyRunningAsAdministrator", resourceCulture);
            }
        }
        
		/// <summary>
		///   Looks up a localized string similar to Impersonating administrator role.
		/// </summary>
		internal static string IDS_MSG_ImpersonatingAdministratorRole {
			get {
				return ResourceManager.GetString("IDS_MSG_ImpersonatingAdministratorRole", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Already running as user.
		/// </summary>
		internal static string IDS_MSG_AlreadyRunningAsUser {
			get {
				return ResourceManager.GetString("IDS_MSG_AlreadyRunningAsUser", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Impersonating user role.
		/// </summary>
		internal static string IDS_MSG_ImpersonatingUserRole {
			get {
				return ResourceManager.GetString("IDS_MSG_ImpersonatingUserRole", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Wrapping runas command.
		/// </summary>
		internal static string IDS_MSG_WrappingRunAsCommand {
			get {
				return ResourceManager.GetString("IDS_MSG_WrappingRunAsCommand", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to ERROR: Invalid option arguments.
		/// </summary>
		internal static string IDS_ERR_InvalidArguments {
			get {
				return ResourceManager.GetString("IDS_ERR_InvalidArguments", resourceCulture);
			}
		}

        /// <summary>
        ///   Looks up a localized string similar to ERROR: Command not found &apos;{0}&apos;.
        /// </summary>
        internal static string IDS_ERR_CommandNotFound {
            get {
                return ResourceManager.GetString("IDS_ERR_CommandNotFound", resourceCulture);
            }
        }
        
		/// <summary>
		///   Looks up a localized string similar to ERROR: Invalid export variables.
		/// </summary>
		internal static string IDS_ERR_InvalidVariables {
			get {
				return ResourceManager.GetString("IDS_ERR_InvalidVariables", resourceCulture);
			}
		}

    }
}
