//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace syswin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("httpget.resource", typeof(resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

		/// <summary>
		///   Looks up a localized string similar to Version {0}.
		/// </summary>
		internal static string IDS_TITLE {
			get {
				return ResourceManager.GetString("IDS_TITLE", resourceCulture);
			}
		}

        /// <summary>
		///   Looks up a localized string similar to Rights: (c) 2014 Francis Korning (manufacture.net).
        /// </summary>
        internal static string IDS_COPYRIGHT {
            get {
                return ResourceManager.GetString("IDS_COPYRIGHT", resourceCulture);
            }
        }

		/// <summary>
		///   Looks up a localized string similar to License: (l) LGPL (Lesser GNU Public License).
		/// </summary>
		internal static string IDS_LICENSING {
			get {
				return ResourceManager.GetString("IDS_LICENSING", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to This usage and options help message (/?).
		/// </summary>
		internal static string IDS_OPT_help {
			get {
				return ResourceManager.GetString("IDS_OPT_help", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to User under which to execute cmd url.
		/// </summary>
		internal static string IDS_OPT_user {
			get {
				return ResourceManager.GetString("IDS_OPT_user", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Password to run cmd url (no prompt).
		/// </summary>
		internal static string IDS_OPT_pass {
			get {
				return ResourceManager.GetString("IDS_OPT_pass", resourceCulture);
			}
		}
			
        /// <summary>
		///   Looks up a localized string similar to Url of file to be retrieved and downloaded.
        /// </summary>
        internal static string IDS_OPT_url {
            get {
                return ResourceManager.GetString("IDS_OPT_url", resourceCulture);
            }
        }

		/// <summary>
		///   Looks up a localized string similar to Directory in which to save downloaded file.
		/// </summary>
		internal static string IDS_OPT_dir {
			get {
				return ResourceManager.GetString("IDS_OPT_dir", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to File name of saved downloaded file (default: index.htm).
		/// </summary>
		internal static string IDS_OPT_file {
			get {
				return ResourceManager.GetString("IDS_OPT_file", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Mime content-type (text|application|image|audio|video).
		/// </summary>
		internal static string IDS_OPT_type {
			get {
				return ResourceManager.GetString("IDS_OPT_type", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Force DOS CRLF line separator (\r\n) for text file types.
		/// </summary>
		internal static string IDS_OPT_winx {
			get {
				return ResourceManager.GetString("IDS_OPT_winx", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Force RISC LFCR line separator (\n\r) for text file types.
		/// </summary>
		internal static string IDS_OPT_risc {
			get {
				return ResourceManager.GetString("IDS_OPT_risc", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Force UNIX LF line separator (\n) for text file types.
		/// </summary>
		internal static string IDS_OPT_unix {
			get {
				return ResourceManager.GetString("IDS_OPT_unix", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Force MAC OS/9 CR line separator (\r) for text file types.
		/// </summary>
		internal static string IDS_OPT_mac9 {
			get {
				return ResourceManager.GetString("IDS_OPT_mac9", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Integer timeout seconds for download.
		/// </summary>
		internal static string IDS_OPT_time {
			get {
				return ResourceManager.GetString("IDS_OPT_time", resourceCulture);
			}
		}


		/// <summary>
		///   Looks up a localized string similar to Creating HTTP request: .
		/// </summary>
		internal static string IDS_MSG_CreatingHttpRequest {
			get {
				return ResourceManager.GetString("IDS_MSG_CreatingHttpRequest", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Exposing network credentiaLs.
		/// </summary>
		internal static string IDS_MSG_ExposingNetworkCredentials {
			get {
				return ResourceManager.GetString("IDS_MSG_ExposingNetworkCredentials", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Fetching HTTP response: .
		/// </summary>
		internal static string IDS_MSG_FetchingHttpResponse {
			get {
				return ResourceManager.GetString("IDS_MSG_FetchingHttpResponse", resourceCulture);
			}
		}

        /// <summary>
        ///   Looks up a localized string similar to Downloading plain text file.
        /// </summary>
        internal static string IDS_MSG_DownloadingPlainTextFile {
            get {
                return ResourceManager.GetString("IDS_MSG_DownloadingPlainTextFile", resourceCulture);
            }
        }
        
		/// <summary>
		///   Looks up a localized string similar to Downloading binary app file.
		/// </summary>
		internal static string IDS_MSG_DownloadingBinaryAppFile {
			get {
				return ResourceManager.GetString("IDS_MSG_DownloadingBinaryAppFile", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Downloaded plain text file.
		/// </summary>
		internal static string IDS_MSG_DownloadedPlainTextFile {
			get {
				return ResourceManager.GetString("IDS_MSG_DownloadedPlainTextFile", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Downloaded binary application file.
		/// </summary>
		internal static string IDS_MSG_DownloadedBinaryAppFile {
			get {
				return ResourceManager.GetString("IDS_MSG_DownloadedBinaryAppFile", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to WARN: MIME content-type mismatch.
		/// </summary>
		internal static string IDS_WARN_MimeContentTypeMismatch {
			get {
				return ResourceManager.GetString("IDS_WARN_MimeContentTypeMismatch", resourceCulture);
			}
		}


		/// <summary>
		///   Looks up a localized string similar to ERROR: MIME content-type unsuported.
		/// </summary>
		internal static string IDS_ERR_MimeContentTypeUnsupported {
			get {
				return ResourceManager.GetString("IDS_ERR_MimeContentTypeUnsupported", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to ERROR: invalid arguments.
		/// </summary>
		internal static string IDS_ERR_InvalidArguments {
			get {
				return ResourceManager.GetString("IDS_ERR_InvalidArguments", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to ERROR: URL file is mandatory.
		/// </summary>
		internal static string IDS_ERR_UrlLMandatory {
			get {
				return ResourceManager.GetString("IDS_ERR_UrlMalndatory", resourceCulture);
			}
		}     

		/// <summary>
		///   Looks up a localized string similar to ERROR: URL Malformed.
		/// </summary>
		internal static string IDS_ERR_UrlLMalformed {
			get {
				return ResourceManager.GetString("IDS_ERR_UrlMalFormed", resourceCulture);
			}
		} 

        /// <summary>
        ///   Looks up a localized string similar to ERROR: URL file not found.
        /// </summary>
        internal static string IDS_ERR_UrlLFileNotFound {
            get {
                return ResourceManager.GetString("IDS_ERR_UrlLFileNotFound", resourceCulture);
            }
        }     

    }

}
